#!/bin/sh
mvn clean package && docker build -t bhavik6187/TestProjectMicroProfile .
docker rm -f TestProjectMicroProfile 2>/dev/null || true && docker run -it --name TestProjectMicroProfile -p 8080:8080 -p 4848:4848 -p 8181:8181 --name TestProjectMicroProfile bhavik6187/TestProjectMicroProfile
